export const AuthRoutes = {
	Login: "/admin/login",
	ForgotPassword: "/admin/forgot-password",
	VerifyOTP: "/admin/verify-otp",
	ResetPassword: "/admin/reset-password",
};

// Admin Routes
export const AdminRoutes = {
	Dashboard: "/admin/dashboard",
	UsersList: "/admin/users/list",
	AdminUsersList: "/admin/admin-users",
	UserDetails: "/admin/user/details",
	LocationList: "/admin/locations",
	QuestionList: "/admin/questions",
	DateList: "/admin/dates",
	DateDetails: "/admin/dates/details",
	DateRatingsList: "/admin/date-ratings",
	GiftList: "/admin/gifts",
	GiftDetails: "/admin/gifts/details",
	UserReportsList: "/admin/user-reports",
	UserReportDetails: "/admin/user-reports/details",
	PaymentList: "/admin/payments",
	Profile: "/admin/profile",
	VerificationList: "/admin/verification",
	VerificationDetails: "/admin/verification/details",
	ComplianceList: "/admin/compliance",
	ComplianceDetails: "/admin/compliance/details",
	TasksList: "/admin/tasks",
	TaskDetails: "/admin/tasks/details",
	AuditLogsList: "/admin/audit-logs",
	AuditLogDetails: "/admin/audit-logs/details",
	NotesList: "/admin/notes",
	VenuesList: "/admin/venues",
	VenuesDetails: "/admin/venues/details",
};
