export const AuthRoutes = {
	Login: "/login",
	ForgotPassword: "/forgot-password",
	VerifyOTP: "/verify-otp",
	ResetPassword: "/reset-password",
};

// Admin Routes
export const AdminRoutes = {
	Dashboard: "/dashboard",
	UsersList: "/users/list",
	AccountDeletionRequests: "/users/deletion-requests",
	AdminUsersList: "/admin-users",
	UserDetails: "/user/details",
	LocationList: "/locations",
	QuestionList: "/questions",
	DateList: "/dates",
	DateDetails: "/dates/details",
	DateRatingsList: "/date-ratings",
	GiftList: "/gifts",
	GiftDetails: "/gifts/details",
	UserReportsList: "/user-reports",
	UserReportDetails: "/user-reports/details",
	SafetyQueue: "/safety-queue",
	SafetyIncidentDetails: "/safety-queue/details",
	PaymentList: "/payments",
	Profile: "/profile",
	Settings: "/settings",
	VerificationList: "/verification",
	VerificationDetails: "/verification/details",
	ComplianceList: "/compliance",
	ComplianceDetails: "/compliance/details",
	TasksList: "/tasks",
	TaskDetails: "/tasks/details",
	AuditLogsList: "/audit-logs",
	AuditLogDetails: "/audit-logs/details",
	NotesList: "/notes",
	VenuesList: "/venues",
	VenuesDetails: "/venues/details",
	UnfreezeRequestsList: "/unfreeze-requests",
	Revenue: "/revenue",
	RolesPermissions: "/roles-permissions",
};
